### ISSUE TITLE
GH-page not published

### ISSUE THREAD

**Issue by RaedsLab** [ricardo-ch/react-easy-sort#1]
**Describe the bug**

The NPM linked GitHub page ricardo-ch.github.io/react-easy-sort/ returns a 404

**To Reproduce**

1. Go to https://www.npmjs.com/package/react-easy-sort
2. Click on Homepage
3. See 404 error

**Expected behavior**

To see the GitHub page.

**Comment by ValentinH** [comment]
Good catch! 😅 This is a bad copy paste when initialising the project.

No there are 2 solutions:
- remove the link
- create a landing page (I was thinking of a simple storybook)

**Comment by RaedsLab** [comment]
Either a storybook or a very basic landing page/demo.

Whatever is simpler.

**Comment by ValentinH** [comment]
Yes bot are fine to me. Would you like to do a PR? 😄

**Comment by RaedsLab** [comment]
Sure thing, but probably not before Friday

**Comment by ValentinH** [comment]
Awesome 🎉 
Do you plan to use storybook or a simple page?

I think I would prefer a storybook as it's easier to maintain. Otherwise, we could create a page similar to https://ricardo-ch.github.io/react-easy-crop. However, using Next instead of Gatsby 😋

**Comment by RaedsLab** [comment]
Maybe just a storybook to start, I don't think the 2 are very different in terms of effort, I just would rather not to have to think about design 😄

**Comment by RaedsLab** [comment]
https://github.com/ricardo-ch/react-easy-sort/pull/2
