### ISSUE TITLE
Support handle/knob

### ISSUE THREAD

**Issue by phaistonian** [ricardo-ch/react-easy-sort#14]
I think the title does it :-)

**Comment by ValentinH** [comment]
Do you have an example API in mind for this feature? How would you like to use it?

**Comment by phaistonian** [comment]
Here's a usecase:

![CleanShot 2021-06-28 at 12 20 35@2x](https://user-images.githubusercontent.com/796530/123612606-6115f180-d80b-11eb-9f5d-90db4eef35d0.png)

In terms of API, I guess you can:

- Introduce a `SortableKnob` wrapper component to be hosted inside `SortableItem`
- Or be able to pass a `knob` property with a ref to `SortableItem` pointing to the ref assigned to a hosted knob element

**Comment by ValentinH** [comment]
I check back the code quickly and this is not trivial to implement. Indeed, the events handling logic is handled at the SortableList level and we would need to maintain a list of all knobs in addition to the items.
Once, this is done, I'm not even sure that events will behave like you would expect outside of the knob.

I'm available to provide guidance if you would like to work a on PR though. 🙂

**Comment by phaistonian** [comment]
Well, it does not look that hard - really.

I can't find time to put on it, though - hectic days down here.

Perhaps later in the near future.
