### ISSUE TITLE
Typescript 4.4 complains about missing module @emotion/core in index.d.ts

### ISSUE THREAD

**Issue by gitter-me** [ricardo-ch/react-easy-sort#23]
**Describe the bug**
Typescript 4.4 complains about missing module @emotion/core in index.d.ts

**To Reproduce**
yarn add react-easy-sort
tsc --watch --noEmit

node_modules/react-easy-sort/index.d.ts:270:18 - error TS2307: Cannot find module '@emotion/core' or its corresponding type declarations.

270     css?: import("@emotion/core").InterpolationWithTheme<any>;

**Expected behavior**
No error from tsc

I'm still puzzled how this happens, since I don't find a reference to emotion in the repo here?

**Comment by ValentinH** [comment]
I just tried installing the latest version and I confirm there is an issue. I'll try to have a look quickly.

**Comment by ValentinH** [comment]
The fix was published in v1.3.3
