### ISSUE TITLE
Confine drag to an axis

### ISSUE THREAD

**Issue by dennis-best** [ricardo-ch/react-easy-sort#27]
As a developer, I'm using this to re-order items in a simple vertical list. So it's potentially jarring or confusing when a user is dragging an element and it can be dragged literally anywhere on the screen.

Ideally, there'd be a prop like dragDirection (any, y-only, x-only)?

Here's a shot of my component vs iOS list re-ordering.

<img width="570" alt="Screen Shot 2022-01-21 at 11 26 43 AM" src="https://user-images.githubusercontent.com/1289418/150588513-85e191ee-93f7-4536-8c04-4092e332a628.png">

![aaaimage](https://user-images.githubusercontent.com/1289418/150588525-ca211b44-b270-4754-82dd-68567b2e8d83.png)

**Comment by ValentinH** [comment]
Yes this would be a nice feature, I like it. Would you like to do a PR for it?

**Comment by ValentinH** [comment]
Starting from [v1.4.0](https://github.com/ricardo-ch/react-easy-sort/releases/tag/v1.4.0), there is a `lockAxis` option.
