### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by kennaku1** [ricardo-ch/react-easy-sort#6]
I am seeing this error when dragging elements within my list. The sorting is correct and the elements are moving as expected but I am getting this error after dropping my element

**Expected behavior**
![image](https://user-images.githubusercontent.com/9734813/112552754-8b759000-8d80-11eb-8080-a9015c3feb74.png)

**Comment by ValentinH** [comment]
Are you able to reproduce this on one of the examples of our storybook? Do you have this on multiple browsers?

Ideally, could you please create a sandbox reproducing the problem?

**Comment by kennaku1** [comment]
I was able to fix this issue by adding a missing key to a parent element. Thanks!

**Comment by ValentinH** [comment]
Do you mean that it was a parent created inside a .map() that was missing a key?

**Comment by darrenjacoby** [comment]
I'm getting the same error, seems like a pretty standard setup. @kennaku1, would you mind elaborating more on your solution?

**Comment by ValentinH** [comment]
Could you please create a sandbox reproducing the problem?

**Comment by sidpremkumar** [comment]
Incase anyone finds this, for me it _might_ have been adding 
```
 customHolderRef={mainRef}
```
field to the `SortableList` that references the parent div. 

Not 100% sure yet, but it feels like it has stopped happening.
