### ISSUE TITLE
Does not work if the image is embedded in the item

### ISSUE THREAD

**Issue by UchihaVeha** [ricardo-ch/react-easy-sort#8]
https://codesandbox.io/s/clever-mestorf-4yvs4?fontsize=14&hidenavigation=1&theme=dark

**Comment by UchihaVeha** [comment]
Forgot about img draggable prop
```
<img src={image?.imageUrl} draggable={false} className={classes.img} />
```

**Comment by sgltkn** [comment]
that's exactly what I need. Thanks @UchihaVeha
